module README where

open import AbelChapmanExtended.Delay
open import AbelChapmanExtended.StrongBisimilarity
open import AbelChapmanExtended.Convergence
open import AbelChapmanExtended.Syntax
open import AbelChapmanExtended.Renaming
open import AbelChapmanExtended.Normalization
open import AbelChapmanExtended.Termination.Eval
open import AbelChapmanExtended.Termination.Readback
open import AbelChapmanExtended.Termination
open import AbelChapmanExtended.Examples

open import TowardsAltArtemov.SyntaxCatholic
open import TowardsAltArtemov.NormalizationCatholic
